version: '3.8'

services:

  nginx_proxy:
    image: nginx:latest
    container_name: nginx_proxy_container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl
      - ./certbot:/var/www/certbot
    depends_on:
      - backend
      - frontend_gantt
      - frontend_admin
    networks:
      - app_network

  certbot:
    image: certbot/certbot
    container_name: certbot_container
    command: certonly --webroot -w /var/www/certbot -d bixco.ir --email mr.amin.zare01@gmail.com --agree-tos --no-eff-email
    volumes:
      - ./ssl:/etc/letsencrypt/live/bixco.ir
      - ./certbot:/var/www/certbot

  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "2900:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: Denizer
      MONGO_INITDB_ROOT_PASSWORD: IchBinAminDenizer
    restart: always
    networks:
      - app_network

  backend:
    build: ./my-backend
    container_name: backend_container
    environment:
      MONGODB_URI: mongodb://Denizer:IchBinAminDenizer@mongodb:27017/projectdb?authSource=admin
      PORT: 5000
    restart: always
    networks:
      - app_network

  frontend_gantt:
    build: ./gantt-chart-project
    container_name: frontend_gantt_container
    restart: always
    networks:
      - app_network

  frontend_admin:
    build: ./project-management-dashboard
    container_name: frontend_admin_container
    restart: always
    networks:
      - app_network

volumes:
  mongodb_data:

networks:
  app_network:
    driver: bridge
